#!/usr/bin/env bash

function __absolute_path ()
{
	local -r directory_path="${1}"

	local value

	if [[ -n ${directory_path} ]]
	then
		value="$(
			python -c "import os,sys; print os.path.abspath(sys.argv[1])" \
			"${directory_path}"
		)"
	fi

	printf -- '%s' "${value}"
}

function __is_valid_apache_content_root ()
{
	local -r directory_path="${1}"
	local -r valid_directory='^\/(?!\/|bin|dev|etc|lib|lib64|lost+found|media|proc|root|sbin|sys|tmp|usr).+$'

	local absolute_path="$(
		__absolute_path \
			"${directory_path}"
	)"

	if grep -qoP "${valid_directory}" <<< "${absolute_path}"
	then
		return 0
	fi

	return 1
}

function __get_absolute_apache_custom_log_location ()
{
	local value="${APACHE_CUSTOM_LOG_LOCATION:-var/log/apache_access_log}"

	if [[ ! ${value} =~ ^[\.]{,2}/ ]]
	then
		printf -v \
			value \
			-- '%s/%s' \
			"${CONTENT_ROOT}" \
			"${value}"
	fi

	printf -- '%s' "${value}"
}

function __get_absolute_apache_error_log_location ()
{
	local value="${APACHE_ERROR_LOG_LOCATION:-var/log/apache_error_log}"

	if [[ ! ${value} =~ ^[\.]{,2}/ ]]
	then
		printf -v \
			value \
			-- '%s/%s' \
			"${CONTENT_ROOT}" \
			"${value}"
	fi

	printf -- '%s' "${value}"
}

function __get_absolute_php_options_session_save_path ()
{
	local -r save_handler="${PHP_OPTIONS_SESSION_SAVE_HANDLER:-files}"

	local value="${PHP_OPTIONS_SESSION_SAVE_PATH:-var/session}"

	if [[ ${save_handler} == files ]] \
		&& [[ ! ${value} =~ ^[\.]{,2}/ ]]
	then
		printf -v \
			value \
			-- '%s/%s' \
			"${CONTENT_ROOT}" \
			"${value}"
	fi

	printf -- '%s' "${value}"
}

function __get_apache_content_root ()
{
	local -r default_value="${1:-/var/www/app}"

	local value="${APACHE_CONTENT_ROOT:-/var/www/app}"

	if ! __is_valid_apache_content_root "${value}"
	then
		value="${default_value}"
	fi

	printf -- '%s' "${value}"
}

function __get_apache_header_x_service_uid ()
{
	local value="${APACHE_HEADER_X_SERVICE_UID}"

	if [[ -n ${value} ]]
	then
		value="${value//'{{HOSTNAME}}'/${HOSTNAME}}"
	fi

	printf -- '%s' "${value}"
}

function __get_apache_server_alias ()
{
	local value="${APACHE_SERVER_ALIAS}"

	if [[ -n ${value} ]]
	then
		value="${value//'{{HOSTNAME}}'/${HOSTNAME}}"
	fi

	printf -- '%s' "${value}"
}

function __get_apache_server_name ()
{
	local value="${APACHE_SERVER_NAME}"

	if [[ -z ${value} ]]
	then
		value="${HOSTNAME}"
	else
		value="${value//'{{HOSTNAME}}'/${HOSTNAME}}"
	fi

	printf -- '%s' "${value}"
}

function main ()
{
	local CONTENT_ROOT="$(
		__get_apache_content_root
	)"

	unset BASH_ENV ENV

	if [[ -z ${HOSTNAME} ]]
	then
		export HOSTNAME="$(
			hostname
		)"
	fi

	export APACHE_CUSTOM_LOG_LOCATION="$(
		__get_absolute_apache_custom_log_location
	)"
	export APACHE_ERROR_LOG_LOCATION="$(
		__get_absolute_apache_error_log_location
	)"
	export APACHE_HEADER_X_SERVICE_UID="$(
		__get_apache_header_x_service_uid
	)"
	export APACHE_SERVER_ALIAS="$(
		__get_apache_server_alias
	)"
	export APACHE_SERVER_NAME="$(
		__get_apache_server_name
	)"
	export PHP_OPTIONS_SESSION_SAVE_PATH="$(
		__get_absolute_php_options_session_save_path
	)"

	if [[ -n ${@} ]]
	then
		exec "${@}"
	fi
}

main "${@}"
