#!/usr/bin/env bash

set -e

function __cleanup ()
{
	__delete_lock
}

function __create_lock ()
{
	if [[ -n ${lock_file} ]]
	then
		touch "${lock_file}"
	fi
}

function __delete_lock ()
{
	if [[ -f ${lock_file} ]]
	then
		rm -f "${lock_file}"
	fi
}

function __get_apache_operating_mode ()
{
	local -r default_value="${1:-production}"

	local value="${APACHE_OPERATING_MODE}"

	if ! __is_valid_apache_operating_mode "${value}"
	then
		value="${default_value}"
	fi

	printf -- '%s' "${value}"
}

function __get_bin ()
{
	local -r bin="/usr/sbin/httpd"
	local mpm="${APACHE_MPM:-prefork}"

	if [[ -f ${bin}.${mpm,,} ]]
	then
		printf -- \
			'%s.%s' \
			"${bin}" \
			"${mpm,,}"
	else
		printf -- \
			'%s' \
			"${bin}"
	fi
}

function __get_options ()
{
	local -r mode="$(
		__get_apache_operating_mode
	)"
	local -r options="${1}"

	printf -- \
		'-c \"ErrorLog /dev/stderr\" -D FOREGROUND -D %s%s%s' \
		"${mode}" \
		"${options:+" "}" \
		"${options}"
}

function __get_proxy ()
{
	printf -- \
		'%s -n %s' \
		"${nice}" \
		"${niceness}"
}

function __is_valid_apache_operating_mode ()
{
	local -r valid_pattern='^(production|development|debug)$'
	local -r value="${1}"

	if [[ ${value} =~ ${valid_pattern} ]]
	then
		return 0
	fi

	return 1
}

function main ()
{
	local -r bootstrap_state_file="/var/lib/misc/httpd-bootstrap"
	local -r bootstrap_timeout="4"
	local -r nice="/bin/nice"
	local -r niceness="10"

	local bin
	local options
	local proxy
	local verbose="false"

	while [[ "${#}" -gt 0 ]]
	do
		case "${1}" in
			-v|--verbose)
				verbose="true"
				shift 1
				;;
		esac
	done

	if [[ -f ${lock_file} ]]
	then
		>&2 printf -- \
			'ERROR: %s lock detected - aborting\n' \
			"${0##*/}"
		exit 1
	fi

	trap __cleanup \
		EXIT INT TERM
	__create_lock

	bin="$(
		__get_bin
	)"
	options="$(
		__get_options
	)"
	proxy="$(
		__get_proxy
	)"

	if [[ ${verbose} == true ]]
	then
		printf -- \
			'INFO: %s waiting on %s\n' \
			"${0##*/}" \
			"${bootstrap_state_file##*/}"
	fi

	set +e
	until [[ -f ${bootstrap_state_file} ]]
	do
		if ! inotifywait -qq \
			-e "create" \
			-t "${bootstrap_timeout}" \
			"${bootstrap_state_file%/*}"
		then
			break
		fi
	done
	set -e

	if ! [[ -f ${bootstrap_state_file} ]]
	then
		>&2 printf -- \
			'ERROR: %s timed out waiting on %s\n' \
			"${0##*/}" \
			"${bootstrap_state_file##*/}"
		exit 1
	fi

	if [[ ${verbose} == true ]]
	then
		printf -- \
			'INFO: %s starting %s\n' \
			"${0##*/}" \
			"${bin##*/}"
	fi

	__cleanup
	trap - \
		EXIT INT TERM

	eval "exec \
		${proxy} \
		${bin} \
		${options}"
}

main "${@}"
