#!/usr/bin/env bash

set -e

function __get_apache_autostart_httpd_bootstrap ()
{
	local -r default_value="${1:-true}"

	local value="${APACHE_AUTOSTART_HTTPD_BOOTSTRAP}"

	if ! __is_valid_apache_autostart_httpd_bootstrap "${value}"
	then
		value="${default_value}"
	fi

	printf -- '%s' "${value}"
}

function __is_valid_apache_autostart_httpd_bootstrap ()
{
	local -r boolean_value='^(true|false)$'
	local -r value="${1}"

	if [[ ${value} =~ ${boolean_value} ]]
	then
		return 0
	fi

	return 1
}

function main ()
{
	local -r autostart_bootstrap="$(
		__get_apache_autostart_httpd_bootstrap
	)"
	local -r bin="/usr/sbin/php-fpm"
	local -r bootstrap_state_file="/var/lib/misc/httpd-bootstrap"
	local -r nice="/bin/nice"
	local -r niceness="10"
	local -r options="-g /var/run/php-fpm/php-fpm.pid -F -O"

	if [[ ${autostart_bootstrap} == false ]]
	then
		# block.
		sleep infinity
	fi

	until [[ -e ${bootstrap_state_file} ]]
	do
		sleep 0.1
	done

	exec ${nice} \
		-n ${niceness} \
		${bin} \
		${options}
}

main "${@}"
