#!/usr/bin/env bash

readonly NICE=/bin/nice
readonly NICENESS="${PHP_FPM_NICENESS:-10}"
readonly PHP_FPM=/usr/sbin/php-fpm

while true; do
	sleep 0.1
	[[ -e /var/lock/subsys/httpd-bootstrap ]] || break
done

exec ${NICE} \
	-n ${NICENESS} \
	${PHP_FPM} \
	-g /var/run/php-fpm/php-fpm.pid \
	-F
