
# Common parameters of create and run targets
define DOCKER_CONTAINER_PARAMETERS
--name $(DOCKER_NAME) \
--restart $(DOCKER_RESTART_POLICY) \
--env "APACHE_AUTOSTART_HTTPD_BOOTSTRAP=$(APACHE_AUTOSTART_HTTPD_BOOTSTRAP)" \
--env "APACHE_AUTOSTART_HTTPD_WRAPPER=$(APACHE_AUTOSTART_HTTPD_WRAPPER)" \
--env "APACHE_AUTOSTART_PHP_FPM_WRAPPER=$(APACHE_AUTOSTART_PHP_FPM_WRAPPER)" \
--env "APACHE_CONTENT_ROOT=$(APACHE_CONTENT_ROOT)" \
--env "APACHE_CUSTOM_LOG_FORMAT=$(APACHE_CUSTOM_LOG_FORMAT)" \
--env "APACHE_CUSTOM_LOG_LOCATION=$(APACHE_CUSTOM_LOG_LOCATION)" \
--env "APACHE_ERROR_LOG_LOCATION=$(APACHE_ERROR_LOG_LOCATION)" \
--env "APACHE_ERROR_LOG_LEVEL=$(APACHE_ERROR_LOG_LEVEL)" \
--env "APACHE_EXTENDED_STATUS_ENABLED=$(APACHE_EXTENDED_STATUS_ENABLED)" \
--env "APACHE_HEADER_X_SERVICE_UID=$(APACHE_HEADER_X_SERVICE_UID)" \
--env "APACHE_LOAD_MODULES=$(APACHE_LOAD_MODULES)" \
--env "APACHE_OPERATING_MODE=$(APACHE_OPERATING_MODE)" \
--env "APACHE_MOD_SSL_ENABLED=$(APACHE_MOD_SSL_ENABLED)" \
--env "APACHE_MPM=$(APACHE_MPM)" \
--env "APACHE_PUBLIC_DIRECTORY=$(APACHE_PUBLIC_DIRECTORY)" \
--env "APACHE_RUN_GROUP=$(APACHE_RUN_GROUP)" \
--env "APACHE_RUN_USER=$(APACHE_RUN_USER)" \
--env "APACHE_SERVER_ALIAS=$(APACHE_SERVER_ALIAS)" \
--env "APACHE_SERVER_NAME=$(APACHE_SERVER_NAME)" \
--env "APACHE_SSL_CERTIFICATE=$(APACHE_SSL_CERTIFICATE)" \
--env "APACHE_SSL_CIPHER_SUITE=$(APACHE_SSL_CIPHER_SUITE)" \
--env "APACHE_SSL_PROTOCOL=$(APACHE_SSL_PROTOCOL)" \
--env "APACHE_SYSTEM_USER=$(APACHE_SYSTEM_USER)" \
--env "PHP_OPTIONS_DATE_TIMEZONE=$(PHP_OPTIONS_DATE_TIMEZONE)"
endef

DOCKER_PUBLISH := $(shell \
	if [[ $(DOCKER_PORT_MAP_TCP_80) != NULL ]]; then printf -- '--publish %s:80\n' $(DOCKER_PORT_MAP_TCP_80); fi; \
	if [[ $(DOCKER_PORT_MAP_TCP_443) != NULL ]] && [[ $(APACHE_MOD_SSL_ENABLED) == true ]]; then printf -- '--publish %s:443\n' $(DOCKER_PORT_MAP_TCP_443); fi; \
	if [[ $(DOCKER_PORT_MAP_TCP_8443) != NULL ]]; then printf -- '--publish %s:8443\n' $(DOCKER_PORT_MAP_TCP_8443); fi; \
)
