#!/usr/bin/env bash

source /etc/httpd-bootstrap.conf

function get_httpd_bin ()
{
	local HTTPD=/usr/sbin/httpd

	if [[ -n ${APACHE_MPM} && ${APACHE_MPM,,} == worker ]] \
		&& [[ -f ${HTTPD}.worker ]]; then
		printf -- \
			'%s.worker' \
			"${HTTPD}"
	else
		printf -- \
			'%s' \
			"${HTTPD}"
	fi
}

HTTPD="$(
	get_httpd_bin
)"
NICE=/bin/nice
NICENESS="${APACHE_NICENESS:-10}"

while true; do 
	sleep 0.1
	[[ -e /tmp/httpd-bootstrap.lock ]] || break
done

exec ${NICE} \
	-n ${NICENESS} \
	${HTTPD} \
	-c "ErrorLog /dev/stdout" \
	-DFOREGROUND \
	-D ${APACHE_OPERATING_MODE:-production}
