# ------------------------------------------------------------------------------
# Constants
# ------------------------------------------------------------------------------
readonly SERVICE_UNIT_ENVIRONMENT_KEYS="
 DOCKER_CONTAINER_OPTS
 DOCKER_IMAGE_PACKAGE_PATH
 DOCKER_IMAGE_TAG
 DOCKER_PORT_MAP_TCP_80
 DOCKER_PORT_MAP_TCP_443
 DOCKER_PORT_MAP_TCP_8443
 ENABLE_HTTPD_BOOTSTRAP
 ENABLE_HTTPD_WRAPPER
 ENABLE_PHP_FPM_WRAPPER
 APACHE_CONTENT_ROOT
 APACHE_CUSTOM_LOG_FORMAT
 APACHE_CUSTOM_LOG_LOCATION
 APACHE_ERROR_LOG_LOCATION
 APACHE_ERROR_LOG_LEVEL
 APACHE_EXTENDED_STATUS_ENABLED
 APACHE_HEADER_X_SERVICE_UID
 APACHE_LOAD_MODULES
 APACHE_OPERATING_MODE
 APACHE_MOD_SSL_ENABLED
 APACHE_MPM
 APACHE_PUBLIC_DIRECTORY
 APACHE_RUN_GROUP
 APACHE_RUN_USER
 APACHE_SERVER_ALIAS
 APACHE_SERVER_NAME
 APACHE_SYSTEM_USER
 PHP_OPTIONS_DATE_TIMEZONE
 PHP_OPTIONS_SESSION_NAME
 PHP_OPTIONS_SESSION_SAVE_HANDLER
 PHP_OPTIONS_SESSION_SAVE_PATH
 SYSTEM_TIMEZONE
"
readonly SERVICE_UNIT_REGISTER_ENVIRONMENT_KEYS="
 REGISTER_ETCD_PARAMETERS
 REGISTER_TTL
 REGISTER_UPDATE_INTERVAL
"

# ------------------------------------------------------------------------------
# Variables
# ------------------------------------------------------------------------------
SERVICE_UNIT_INSTALL_TIMEOUT="${SERVICE_UNIT_INSTALL_TIMEOUT:-5}"
